language: julia

os:
  - osx

julia:
  - 1.4

notifications:
  email: false

after_success:
  - julia -e 'using Pkg; cd(Pkg.dir("Nash")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())';

jobs:
  include:
    - stage: "Documentation"
      julia: 1.4
      os: linux
      script:
        - pip3 install simpy
        - julia --project=docs/ -e 'using Pkg; Pkg.instantiate();
                                    Pkg.develop(PackageSpec(path=pwd()))'
        - julia --project=docs/ docs/make.jl
      after_success: skip